.PHONY: clean All

All:
	@echo "----------Building project:[ TicTacToe_Game_Exercise - Debug ]----------"
	@cd "TicTacToe_Game_Exercise" && "$(MAKE)" -f  "TicTacToe_Game_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ TicTacToe_Game_Exercise - Debug ]----------"
	@cd "TicTacToe_Game_Exercise" && "$(MAKE)" -f  "TicTacToe_Game_Exercise.mk" clean
