.PHONY: clean All

All:
	@echo "----------Building project:[ Fget_function_Use_case - Debug ]----------"
	@cd "Fget_function_Use_case" && "$(MAKE)" -f  "Fget_function_Use_case.mk"
clean:
	@echo "----------Cleaning project:[ Fget_function_Use_case - Debug ]----------"
	@cd "Fget_function_Use_case" && "$(MAKE)" -f  "Fget_function_Use_case.mk" clean
