.PHONY: clean All

All:
	@echo "----------Building project:[ Exercise_11_Fsetpos_Fgetpos - Debug ]----------"
	@cd "Exercise_11_Fsetpos_Fgetpos" && "$(MAKE)" -f  "Exercise_11_Fsetpos_Fgetpos.mk"
clean:
	@echo "----------Cleaning project:[ Exercise_11_Fsetpos_Fgetpos - Debug ]----------"
	@cd "Exercise_11_Fsetpos_Fgetpos" && "$(MAKE)" -f  "Exercise_11_Fsetpos_Fgetpos.mk" clean
