.PHONY: clean All

All:
	@echo "----------Building project:[ Multidimensional_Exercise - Debug ]----------"
	@cd "Multidimensional_Exercise" && "$(MAKE)" -f  "Multidimensional_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Multidimensional_Exercise - Debug ]----------"
	@cd "Multidimensional_Exercise" && "$(MAKE)" -f  "Multidimensional_Exercise.mk" clean
