.PHONY: clean All

All:
	@echo "----------Building project:[ Command_line_arguments - Debug ]----------"
	@cd "Command_line_arguments" && "$(MAKE)" -f  "Command_line_arguments.mk"
clean:
	@echo "----------Cleaning project:[ Command_line_arguments - Debug ]----------"
	@cd "Command_line_arguments" && "$(MAKE)" -f  "Command_line_arguments.mk" clean
