.PHONY: clean All

All:
	@echo "----------Building project:[ Counting_Characters_In_String_Pointers_Exercise_4 - Debug ]----------"
	@cd "Counting_Characters_In_String_Pointers_Exercise_4" && "$(MAKE)" -f  "Counting_Characters_In_String_Pointers_Exercise_4.mk"
clean:
	@echo "----------Cleaning project:[ Counting_Characters_In_String_Pointers_Exercise_4 - Debug ]----------"
	@cd "Counting_Characters_In_String_Pointers_Exercise_4" && "$(MAKE)" -f  "Counting_Characters_In_String_Pointers_Exercise_4.mk" clean
