.PHONY: clean All

All:
	@echo "----------Building project:[ DebuggerTest - Debug ]----------"
	@cd "DebuggerTest" && "$(MAKE)" -f  "DebuggerTest.mk"
clean:
	@echo "----------Cleaning project:[ DebuggerTest - Debug ]----------"
	@cd "DebuggerTest" && "$(MAKE)" -f  "DebuggerTest.mk" clean
