.PHONY: clean All

All:
	@echo "----------Building project:[ Pass_by_refrence_Square_Root_Exercise - Debug ]----------"
	@cd "Pass_by_refrence_Square_Root_Exercise" && "$(MAKE)" -f  "Pass_by_refrence_Square_Root_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Pass_by_refrence_Square_Root_Exercise - Debug ]----------"
	@cd "Pass_by_refrence_Square_Root_Exercise" && "$(MAKE)" -f  "Pass_by_refrence_Square_Root_Exercise.mk" clean
