.PHONY: clean All

All:
	@echo "----------Building project:[ Loops_Exercise - Debug ]----------"
	@cd "Loops_Exercise" && "$(MAKE)" -f  "Loops_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Loops_Exercise - Debug ]----------"
	@cd "Loops_Exercise" && "$(MAKE)" -f  "Loops_Exercise.mk" clean
