.PHONY: clean All

All:
	@echo "----------Building project:[ Converting_String_Functions - Debug ]----------"
	@cd "Converting_String_Functions" && "$(MAKE)" -f  "Converting_String_Functions.mk"
clean:
	@echo "----------Cleaning project:[ Converting_String_Functions - Debug ]----------"
	@cd "Converting_String_Functions" && "$(MAKE)" -f  "Converting_String_Functions.mk" clean
