.PHONY: clean All

All:
	@echo "----------Building project:[ Pointer_Item_Exercise - Debug ]----------"
	@cd "Pointer_Item_Exercise" && "$(MAKE)" -f  "Pointer_Item_Exercise.mk"
clean:
	@echo "----------Cleaning project:[ Pointer_Item_Exercise - Debug ]----------"
	@cd "Pointer_Item_Exercise" && "$(MAKE)" -f  "Pointer_Item_Exercise.mk" clean
