.PHONY: clean All

All:
	@echo "----------Building project:[ SizeOf_Operator - Debug ]----------"
	@cd "SizeOf_Operator" && "$(MAKE)" -f  "SizeOf_Operator.mk"
clean:
	@echo "----------Cleaning project:[ SizeOf_Operator - Debug ]----------"
	@cd "SizeOf_Operator" && "$(MAKE)" -f  "SizeOf_Operator.mk" clean
